#
# OpenShift diagnostics image
# Used by network diagnostics (oadm diagnostics NetworkCheck)
#
# The standard name for this image is openshift/diagnostics-deployer

FROM docker.io/busybox

COPY scripts/openshift-network-debug /usr/bin/
